steps:
- name: "gcr.io/cloud-builders/docker"
  args:
    - build
    - --tag
    - "gcr.io/$_FIREBASE_PROJECT_ID/$_SERVICE_NAME:$_GITHUB_SHA"
    - --build-arg
    - FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID
    - --build-arg
    - FIREBASE_API_KEY=$_FIREBASE_API_KEY
    - --build-arg
    - FIREBASE_AUTH_DOMAIN=$_FIREBASE_AUTH_DOMAIN
    - --build-arg
    - FIREBASE_DATABASE_URL=$_FIREBASE_DATABASE_URL
    - --build-arg
    - FIREBASE_STORAGE_BUCKET=$_FIREBASE_STORAGE_BUCKET
    - --build-arg
    - FIREBASE_MESSAGING_SENDER_ID=$_FIREBASE_MESSAGING_SENDER_ID
    - --build-arg
    - FIREBASE_APP_ID=$_FIREBASE_APP_ID
    - --build-arg
    - FIREBASE_MEASUREMENT_ID=$_FIREBASE_MEASUREMENT_ID
