steps:
- name: "gcr.io/cloud-builders/docker"
  args:
    - build
    - --tag
    - "gcr.io/$$FIREBASE_PROJECT_ID/$$SERVICE_NAME:$$GITHUB_SHA"
    - --build-arg
    - FIREBASE_PROJECT_ID=$$FIREBASE_PROJECT_ID
    - --build-arg
    - FIREBASE_API_KEY=$$FIREBASE_API_KEY
    - --build-arg
    - FIREBASE_AUTH_DOMAIN=$$FIREBASE_AUTH_DOMAIN
    - --build-arg
    - FIREBASE_DATABASE_URL=$$FIREBASE_DATABASE_URL
    - --build-arg
    - FIREBASE_STORAGE_BUCKET=$$FIREBASE_STORAGE_BUCKET
    - --build-arg
    - FIREBASE_MESSAGING_SENDER_ID=$$FIREBASE_MESSAGING_SENDER_ID
    - --build-arg
    - FIREBASE_APP_ID=$$FIREBASE_APP_ID
    - --build-arg
    - FIREBASE_MEASUREMENT_ID=$$FIREBASE_MEASUREMENT_ID
