name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - master

env:
  GOOGLE_CLOUD_REGION: asia-northeast1
  SERVICE_NAME: app

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}

    - name: Build
      run: |-
        gcloud config set builds/use_kaniko True

        gcloud builds submit \
          --timeout="30m" \
          --quiet \
          --substitutions=FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
          --substitutions=FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} \
          --substitutions=FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }} \
          --substitutions=FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }} \
          --substitutions=FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} \
          --substitutions=FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} \
          --substitutions=FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} \
          --substitutions=FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}

    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$GOOGLE_CLOUD_REGION" \
          --image "gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated
